# Site
name: 'Health Well Mercantile'
description: 'Health Well Mercantile is a free Jekyll theme for awesome people like you, Medium like.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/'
email: 'contact@healthwellmercantile.co.uk'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=46bba9da9164d412c736cac44b288369-us10&amp;id=381c7b4d16'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    mark:
      name:           Mark
      site:           https://healthwellmercantile.co.uk
      avatar:         /assets/images/mark.png
      bio:            "Hi, I am Mark, the Director/Author of Health Well Mercantile. Contact me at mark@healthwellmercantile.co.uk"
      email:          contact@healthwellmercantile.co.uk
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: mark
      avatar: /assets/images/mark.png
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
